### ISSUE TITLE
Remove 'static bound

### ISSUE THREAD

**Issue by mahkoh** [mahkoh/comm#8]
Requires all consumers and producers to get a lifetime parameter.

**Comment by marcusklaas** [comment]
Apologies for my ignorance, but why are these parameters necessary? It seems they refer to the lifetime of the values being sent over the channel. How should one interpret these parameters?

**Comment by mahkoh** [comment]
It's the lifetime of the type `T` that's being sent. E.g.

``` rust
extern crate comm;

use std::{thread};

fn main() {
    let mut var = 0;
    {
        let (send, recv) = comm::spsc::one_space::new();
        send.send(&mut var).unwrap();
        let _ = thread::scoped(move || {
            let var = recv.recv_sync().unwrap();
            *var = 1;
        });
    }
    assert_eq!(var, 1);
}
```

The lifetime of `send` and `recv` is the lifetime of `var`.

This allows you to send references to stack variables to other (scoped) threads. See http://en.wikipedia.org/wiki/Fork%E2%80%93join_model.

It's unfortunate that you now have to write `'static` most of the time but I don't know if it's possible to avoid this.

**Comment by marcusklaas** [comment]
Ah, that's very cool. Thanks for the explanation!
